# Generated by Django 5.0 on 2024-01-04 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("sub_Categories", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="SalerDetail",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(default="default.png", upload_to="user_photos"),
                ),
                ("mobile", models.CharField(max_length=10, null=True)),
                ("gst_Number", models.CharField(max_length=15, null=True)),
                (
                    "alternate_mobile",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("shop_Address", models.TextField()),
                ("pincode", models.CharField(max_length=6, null=True)),
                ("landmark", models.CharField(blank=True, max_length=500, null=True)),
                ("locality", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("Githurai", "Githurai"),
                            ("Kahawa", "Kahawa"),
                            ("Ruiru", "Ruiru"),
                            ("Juja", "Juja"),
                            ("Kasarani", "Kasarani"),
                            ("Thika", "Thika"),
                            ("Kayole", "Kayole"),
                            ("Eastleigh", "Eastleigh"),
                            ("CBD", "CBD"),
                            ("Westlands", "Westlands"),
                            ("Kibera", "Kibera"),
                            ("Kayole", "Kayole"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("account_Holder_Name", models.CharField(max_length=50, null=True)),
                ("account_Number", models.CharField(max_length=20, null=True)),
                ("ifsc_Code", models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SellerSlider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50, null=True)),
                ("image", models.ImageField(upload_to="seller_slider_img")),
                ("url", models.CharField(default="#", max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(default="General", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("pending_payment", "Pending Payment"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("student_message", models.TextField(blank=True, null=True)),
                ("tutor_message", models.TextField(blank=True, null=True)),
                ("duration", models.CharField(default="1", max_length=5)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("payment_not_initiated", "Payment Not Initiated"),
                            ("payment_initiated", "Payment Initiated"),
                            ("payment_pending", "Payment Pending"),
                            ("payment_completed", "Payment Completed"),
                            ("payment_failed", "Payment Failed"),
                        ],
                        default="payment_not_initiated",
                        max_length=30,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="student_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingPayments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reference", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "confirmation_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_status_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_account",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "merchant_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("currency", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "order_tracking_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("create_date", models.DateTimeField(blank=True, null=True)),
                ("message", models.CharField(blank=True, max_length=100, null=True)),
                ("status_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "payment_status_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="saler.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Course Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Course Description"
                    ),
                ),
                (
                    "thumbnail",
                    models.FileField(blank=True, null=True, upload_to="course_images"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "subtitles",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Other Languages or Subtitles",
                    ),
                ),
                ("course_content", models.TextField(blank=True, null=True)),
                (
                    "preview",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="course_previews",
                        verbose_name="Course Preview Video",
                    ),
                ),
                ("prerequisite", models.TextField(blank=True, null=True)),
                ("date_uploaded", models.DateField(auto_now_add=True)),
                (
                    "course_files",
                    models.FileField(blank=True, null=True, upload_to="course_files"),
                ),
                (
                    "other_information",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Additional Information about the Course",
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "customers",
                    models.ManyToManyField(
                        blank=True, null=True, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_tutor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MainFinanceAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")],
                        default="deposit",
                        max_length=20,
                    ),
                ),
                (
                    "amount_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "last_withdraw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "last_deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "last_deposit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="saler.bookingpayments",
                    ),
                ),
            ],
            options={
                "get_latest_by": "id",
            },
        ),
        migrations.CreateModel(
            name="MyCart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=100)),
                ("number", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(default="", max_length=50)),
                ("saler", models.CharField(default="lokolingo@admin", max_length=100)),
                ("products", models.CharField(max_length=50)),
                ("size", models.CharField(default="", max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("On The Way", "On The Way"),
                            ("Delivered", "Delivered"),
                            ("Cancel", "Cancel"),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_id2", models.CharField(default="", max_length=100)),
                ("product_name", models.CharField(default="", max_length=100)),
                ("prod_seller", models.CharField(default="", max_length=100)),
                ("subcategory", models.CharField(default="", max_length=50)),
                ("price", models.IntegerField(default=0)),
                ("desc", models.TextField()),
                (
                    "gst",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("3", "3"),
                            ("5", "5"),
                            ("12", "12"),
                            ("18", "18"),
                            ("28", "28"),
                        ],
                        default="0",
                        max_length=3,
                    ),
                ),
                ("pub_date", models.DateField(auto_now=True)),
                (
                    "image1",
                    models.ImageField(
                        default="", null=True, upload_to="products/images"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="products/images"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="products/images"
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="products/images"
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="products/images"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="saler.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="dow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                (
                    "product",
                    models.OneToOneField(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saler.product",
                        verbose_name="Product Id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="saler.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=20)),
                ("quantity", models.IntegerField(default=0, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="saler.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "thumbnail",
                    models.FileField(default="default.png", upload_to="skill_images"),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="saler.skillcategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="saler.skill",
            ),
        ),
        migrations.CreateModel(
            name="TimeSlots",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_booked", models.BooleanField(default=False)),
                ("date", models.DateField()),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="slots",
                        to="saler.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="trend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "product",
                    models.OneToOneField(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saler.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorFinanceAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "last_withdraw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "last_deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "last_deposit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="saler.bookingpayments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("pending_approval", "Pending Approval"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("meet_url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "payments",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="session",
                        to="saler.bookingpayments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WholeSaleProduct",
            fields=[
                ("product_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(default="", max_length=100)),
                ("prod_seller", models.CharField(default="", max_length=100)),
                ("subcategory", models.CharField(default="", max_length=50)),
                ("price", models.IntegerField(default=0)),
                ("desc", models.TextField()),
                (
                    "size",
                    models.TextField(verbose_name="Size Avialabe(Separated by Comma)"),
                ),
                (
                    "color",
                    models.TextField(verbose_name="Enter Color Separated by Comma"),
                ),
                ("min_Quantity", models.IntegerField(default=0, null=True)),
                ("pub_date", models.DateField(auto_now=True)),
                (
                    "image1",
                    models.ImageField(
                        default="", null=True, upload_to="products/images"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="products/images"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="products/images"
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="products/images"
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="products/images"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="saler.category",
                        verbose_name="Category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WholeSaleProductOrders",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(default="", max_length=50)),
                ("products", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("On The Way", "On The Way"),
                            ("Delivered", "Delivered"),
                            ("Cancel", "Cancel"),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WithdrawFunds",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_initiated", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("processed", "Processed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="saler.tutorfinanceaccount",
                    ),
                ),
            ],
        ),
    ]
