# Generated by Django 5.0 on 2024-01-05 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("saler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingpayments",
            name="booking",
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="content_type",
            field=models.ForeignKey(
                default=-2020,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="object_id",
            field=models.PositiveBigIntegerField(default=-2020),
            preserve_default=False,
        ),
    ]
