# Generated by Django 5.0 on 2024-01-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0003_alter_bookingpayments_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpayments",
            name="object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
