# Generated by Django 5.0 on 2024-01-06 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0004_alter_bookingpayments_object_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingpayments",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="bookingpayments",
            name="object_id",
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="saler.booking",
            ),
        ),
    ]
