# Generated by Django 5.0 on 2024-01-07 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0005_remove_bookingpayments_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpayments",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="saler.course",
            ),
        ),
    ]
