# Generated by Django 5.0 on 2024-01-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0007_coursesection_sectionvideo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sectionvideo",
            old_name="video_file",
            new_name="resource_file",
        ),
        migrations.AddField(
            model_name="coursesection",
            name="index",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Index (used in ordering)"
            ),
        ),
        migrations.AddField(
            model_name="sectionvideo",
            name="index",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Index (used in ordering)"
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Section Title"),
        ),
        migrations.AlterField(
            model_name="sectionvideo",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Video Title"),
        ),
    ]
