# Generated by Django 5.0 on 2024-01-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0009_alter_coursesection_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorsession",
            name="session_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
