# Generated by Django 5.0 on 2024-01-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0010_alter_tutorsession_session_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserating",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="saler.course",
            ),
        ),
    ]
