# Generated by Django 5.0 on 2024-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0011_courserating_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courserating",
            name="rating",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                max_length=10,
            ),
        ),
    ]
