# Generated by Django 5.0 on 2024-01-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0012_alter_courserating_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_files",
        ),
        migrations.AlterField(
            model_name="skill",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Topic"),
        ),
    ]
