# Generated by Django 5.0 on 2024-01-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0013_remove_course_course_files_alter_skill_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="thumbnail",
        ),
    ]
