# Generated by Django 5.0 on 2024-01-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0014_remove_skill_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.TextField(verbose_name="Topic Information"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Topic/Subject"),
        ),
    ]
