# Generated by Django 4.2.7 on 2023-11-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0021_alter_orders_saler'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleproduct',
            name='prod_seller',
            field=models.CharField(default='', max_length=100),
        ),
    ]
