# Generated by Django 4.2.7 on 2023-11-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0023_product_prod_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerdetail',
            name='shop_Name',
        ),
    ]
