# Generated by Django 5.0 on 2023-12-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0027_skillcategory_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="thumbnail",
        ),
    ]
