# Generated by Django 5.0 on 2023-12-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0028_remove_skill_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="skill_images"),
        ),
    ]
