# Generated by Django 5.0 on 2023-12-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0030_alter_skill_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="thumbnail",
            field=models.FileField(
                blank=True, default="default.png", null=True, upload_to="skill_images"
            ),
        ),
    ]
