# Generated by Django 5.0 on 2023-12-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0031_alter_skill_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="thumbnail",
            field=models.FileField(default="default.png", upload_to="skill_images"),
        ),
    ]
