# Generated by Django 5.0 on 2023-12-14 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0032_alter_skill_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlots",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("date", models.DateField()),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="saler.skill"
                    ),
                ),
            ],
        ),
    ]
