# Generated by Django 5.0 on 2023-12-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0034_timeslots_is_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslots",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="slots",
                to="saler.skill",
            ),
        ),
    ]
