# Generated by Django 5.0 on 2023-12-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0035_timeslots_meet_timeslots_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslots',
            old_name='meet',
            new_name='meet_url',
        ),
    ]
