# Generated by Django 5.0 on 2023-12-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0036_rename_meet_timeslots_meet_url'),
        ('saler', '0038_alter_salerdetail_user'),
    ]

    operations = [
    ]
