# Generated by Django 5.0 on 2023-12-21 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0047_bookingpayments_tutoraccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpayments",
            name="reference",
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
