# Generated by Django 5.0 on 2023-12-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0048_bookingpayments_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpayments",
            name="confirmation_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="create_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="currency",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="merchant_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="message",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="order_tracking_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="payment_account",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="payment_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="payment_status_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="payment_status_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bookingpayments",
            name="status_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="bookingpayments",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bookingpayments",
            name="reference",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
