# Generated by Django 5.0 on 2023-12-22 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0049_bookingpayments_confirmation_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpayments",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="saler.booking"
            ),
        ),
    ]
