# Generated by Django 5.0 on 2023-12-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0050_alter_bookingpayments_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookingpayments",
            old_name="session",
            new_name="booking",
        ),
    ]
