# Generated by Django 5.0 on 2023-12-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0051_rename_session_bookingpayments_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpayments",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="saler.booking",
            ),
        ),
    ]
