# Generated by Django 5.0 on 2023-12-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0053_remove_booking_tutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
