# Generated by Django 5.0 on 2023-12-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0055_tutorsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorsession",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
