# Generated by Django 5.0 on 2023-12-23 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0056_tutorsession_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorsession",
            name="payments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="saler.bookingpayments",
            ),
        ),
    ]
