# Generated by Django 5.0 on 2023-12-26 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0059_alter_tutorsession_payments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutoraccount",
            old_name="last_deposit_amount",
            new_name="last_deposit",
        ),
        migrations.RemoveField(
            model_name="tutoraccount",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="tutoraccount",
            name="tutor",
        ),
        migrations.AddField(
            model_name="tutoraccount",
            name="amount_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="MainAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "last_deposit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="saler.bookingpayments",
                    ),
                ),
            ],
        ),
    ]
