# Generated by Django 5.0 on 2023-12-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0060_rename_last_deposit_amount_tutoraccount_last_deposit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainaccount",
            name="last_withdraw",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="tutoraccount",
            name="last_withdraw",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
