# Generated by Django 5.0 on 2023-12-28 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0060_rename_last_deposit_amount_tutoraccount_last_deposit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutoraccount",
            name="last_deposit",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="rate",
        ),
        migrations.CreateModel(
            name="MainFinanceAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")],
                        default="deposit",
                        max_length=20,
                    ),
                ),
                (
                    "amount_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "last_withdraw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "last_deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "last_deposit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="saler.bookingpayments",
                    ),
                ),
            ],
            options={
                "get_latest_by": "id",
            },
        ),
        migrations.CreateModel(
            name="TutorFinanceAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "last_withdraw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "last_deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "last_deposit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="saler.bookingpayments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WithdrawFunds",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_initiated", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("processed", "Processed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="saler.tutorfinanceaccount",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MainAccount",
        ),
        migrations.DeleteModel(
            name="TutorAccount",
        ),
    ]
