# Generated by Django 5.0 on 2024-01-01 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0061_remove_tutoraccount_last_deposit_remove_skill_rate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "thumbnail",
                    models.FileField(blank=True, null=True, upload_to="course_images"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("subtitles", models.TextField(blank=True, null=True)),
                ("course_content", models.TextField(blank=True, null=True)),
                (
                    "preview",
                    models.FileField(
                        blank=True, null=True, upload_to="course_previews"
                    ),
                ),
                ("prerequisite", models.TextField(blank=True, null=True)),
                ("date_uploaded", models.DateField(auto_now_add=True)),
                (
                    "course_files",
                    models.FileField(blank=True, null=True, upload_to="course_files"),
                ),
                ("other_information", models.TextField(blank=True, null=True)),
                ("customers", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "tutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_tutor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
