# Generated by Django 5.0 on 2023-12-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0061_mainaccount_last_withdraw_tutoraccount_last_withdraw"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MainAccount",
            new_name="MainFinanceAccount",
        ),
        migrations.RenameModel(
            old_name="TutorAccount",
            new_name="TutorFinanceAccount",
        ),
    ]
