# Generated by Django 5.0 on 2024-01-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0062_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
