# Generated by Django 5.0 on 2023-12-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0062_rename_mainaccount_mainfinanceaccount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="rate",
        ),
    ]
