# Generated by Django 5.0 on 2024-01-02 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saler", "0064_course_date_added_alter_course_customers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="date_added",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
