# Generated by Django 5.0 on 2024-01-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoruserdetails",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cvs"),
        ),
    ]
