# Generated by Django 5.0 on 2024-01-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutoruserdetails",
            name="availability",
            field=models.CharField(max_length=50, verbose_name="General Availability"),
        ),
    ]
