# Generated by Django 5.0 on 2024-01-09 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_tutoruserdetails_cv"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_number", models.CharField(max_length=50)),
                (
                    "subjects",
                    models.TextField(verbose_name="Subjects/Topics needing assistance"),
                ),
                (
                    "grade_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_tutoring_format",
                    models.CharField(
                        choices=[
                            ("one on one", "One on One"),
                            ("group", "group"),
                            ("flexible", "flexible"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "availability",
                    models.TextField(verbose_name="Prefered Days and Times"),
                ),
                ("duration_per_session", models.CharField(max_length=100)),
                ("budget_range", models.CharField(max_length=100)),
                ("payment_method", models.CharField(max_length=100)),
                ("languages_preference", models.CharField(max_length=100)),
                ("qualifications_desired", models.CharField(max_length=100)),
                (
                    "accept_terms",
                    models.BooleanField(
                        default=False, verbose_name="Accept Terms and Conditions"
                    ),
                ),
                (
                    "privacy_preference",
                    models.CharField(
                        choices=[
                            (
                                "Share my details with matched tutors",
                                "Share my details with matched tutors",
                            ),
                            (
                                "Remain anonymous untill matching",
                                "Remain anonymous untill matching",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
