# Generated by Django 5.0 on 2024-01-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_tutoruserdetails_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="day",
            field=models.DateField(blank=True, null=True, verbose_name="day of Event"),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Any Notes"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Time"),
        ),
    ]
