# Generated by Django 5.0 on 2024-01-09 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_studentdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdetails",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Student"), ("tutor", "Tutor")],
                default=django.utils.timezone.now,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
