# Generated by Django 5.0 on 2024-01-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_event_day_alter_event_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutoruserdetails",
            name="availability",
            field=models.CharField(max_length=100, verbose_name="General Availability"),
        ),
    ]
