# Generated by Django 4.2.7 on 2023-11-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userdetail_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='locality',
            field=models.DateField(null=True),
        ),
    ]
