# Generated by Django 5.0 on 2024-01-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_studentdetails_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="preferred_tutoring_format",
            field=models.CharField(
                choices=[
                    ("one on one", "One on One"),
                    ("group", "Group"),
                    ("flexible", "Flexible"),
                ],
                max_length=50,
            ),
        ),
    ]
