# Generated by Django 5.0 on 2024-01-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_studentdetails_preferred_tutoring_format"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentdetails",
            name="user_type",
        ),
    ]
