# Generated by Django 4.2.7 on 2023-11-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userdetail_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
