# Generated by Django 5.0 on 2024-01-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_studentdetails_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutoruserdetails",
            name="cancellation_policy",
        ),
    ]
