# Generated by Django 5.0 on 2023-12-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_userdetail_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetail",
            name="area",
        ),
        migrations.AddField(
            model_name="userdetail",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Student"), ("tutor", "Tutor")],
                default=-2020,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
