# Generated by Django 5.0 on 2023-12-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_userdetail_area_userdetail_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetail",
            name="user_type",
        ),
        migrations.AddField(
            model_name="userdetail",
            name="area",
            field=models.CharField(
                choices=[("Beginner", "Beginner"), ("Intermediate", "Intermediate")],
                max_length=50,
                null=True,
            ),
        ),
    ]
