# Generated by Django 5.0 on 2023-12-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_userdetail_user_type_userdetail_area"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetail",
            name="area",
        ),
        migrations.RemoveField(
            model_name="userdetail",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="userdetail",
            name="landmark",
        ),
        migrations.RemoveField(
            model_name="userdetail",
            name="locality",
        ),
        migrations.AddField(
            model_name="userdetail",
            name="country",
            field=models.CharField(default="Kenya", max_length=100),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="identification",
            field=models.FileField(default=-2020, upload_to="tutor_documents"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdetail",
            name="photo",
            field=models.FileField(default="default.png", upload_to="tutor_photos"),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="profile_description",
            field=models.TextField(default=-2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdetail",
            name="rate_per_hour",
            field=models.DecimalField(decimal_places=2, default=-2020, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdetail",
            name="tutoring_experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Student"), ("tutor", "Tutor")],
                default=-2020,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
