# Generated by Django 5.0 on 2023-12-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_userdetail_area_remove_userdetail_dob_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdetail",
            old_name="identification",
            new_name="identification_document",
        ),
    ]
