# Generated by Django 5.0 on 2023-12-20 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_tutorrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrating',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorrating',
            name='tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
