# Generated by Django 5.0 on 2023-12-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_tutorrating_student_alter_tutorrating_tutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorrating",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
